### ISSUE TITLE
Changes in API since 0.2.15 version

### ISSUE THREAD

**Issue by GLEF1X** [GLEF1X/glQiwiApi#3]
# :cupid:Changes since version 0.2.15:

- [x] Webhooks and handlers were added.
- [x] The documentation was rewritten from scratch.
- [x] Unit tests were written for the QIWI API.
- [x] `QIWI Maps API` coverage was added.
- [x] Query caching is still in beta testing now, but it will be released as stable from the 0.2.3 version of `glQiwiApi`.
- [x] Added `sync` "connector" function to run any async functions in synchronous code
---
# ⛏TODO: 
- [x] poetry coverage
